WITH BIKE AS (
    SELECT
        REPLACE(RIDE_ID, '"', '') AS RIDE_ID,
        REPLACE(RIDEABLE_TYPE, '"', '') AS RIDEABLE_TYPE,
        TRY_TO_TIMESTAMP(REPLACE(STARTED_AT, '"', '')) AS STARTED_AT,
        TRY_TO_TIMESTAMP(REPLACE(ENDED_AT, '"', '')) AS ENDED_AT,
        REPLACE(START_STATION_NAME, '"', '') AS START_STATION_NAME,
        REPLACE(START_STATION_ID, '"', '') AS START_STATION_ID,
        REPLACE(END_STATION_NAME, '"', '') AS END_STATION_NAME,
        REPLACE(END_STATION_ID, '"', '') AS END_STATION_ID,
        START_LAT,
        START_LNG,
        END_LAT,
        END_LNG,
        REPLACE(MEMBER_CASUAL, '"', '') AS MEMBER_CASUAL
    FROM {{ source('demo', 'bike') }}
    WHERE RIDE_ID IS NOT NULL
      AND RIDE_ID NOT LIKE '%bikeid%'
      AND STARTED_AT IS NOT NULL
      AND STARTED_AT NOT LIKE '%starttime%'
      AND ENDED_AT IS NOT NULL
)

SELECT
    *
FROM BIKE
WHERE STARTED_AT IS NOT NULL
  AND ENDED_AT IS NOT NULL
  AND STARTED_AT < ENDED_AT  -- 有効な時間範囲のみ